// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Windows.Forms.Tests;

// These tests shell out to the "dotnet" CLI, hit NuGet for restore, and perform a full build of the
// generated project. They are inherently slower and less isolated than a typical unit test, and require
// the WinForms SDK templates and .NET SDK to be installed in the environment running the tests.
[Trait("Category", "OuterLoop")]
public class TemplateTests
{
    [Theory]
    [InlineData("winforms", "TestWinFormsApp", "Program.cs", "Form1.cs")]
    [InlineData("winformslib", "TestWinFormsLib", "Class1.cs")]
    public void WinFormsTemplate_CreatesAndBuilds(string templateName, string projectName, params string[] expectedFiles)
    {
        string tempDir = DotNetCliHelper.CreateTempFolder();
        try
        {
            DotNetCliHelper.CommandResult newResult = DotNetCliHelper.RunCommand("dotnet", $"new {templateName} -n {projectName}", tempDir);
            Assert.True(newResult.ExitCode == 0, $"'dotnet new {templateName}' failed.{Environment.NewLine}{newResult}");

            string projectDir = Path.Combine(tempDir, projectName);
            foreach (string expectedFile in expectedFiles)
            {
                Assert.True(File.Exists(Path.Combine(projectDir, expectedFile)), $"Expected '{expectedFile}' was not generated by the '{templateName}' template.");
            }

            DotNetCliHelper.CommandResult buildResult = DotNetCliHelper.RunCommand("dotnet", "build", projectDir);
            Assert.True(buildResult.ExitCode == 0, $"'dotnet build' of the generated '{templateName}' template failed.{Environment.NewLine}{buildResult}");
        }
        finally
        {
            DotNetCliHelper.Dispose(tempDir);
        }
    }
}
